### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by Coderranker** [s-u/Rserve#104]
Hi All,

I am trying to use the authentication feature in Rserve.
This is how my files look now -

Rserv.conf 
      auth required
      plaintext disable
      pwdfile credfile
      remote enable

user/pass in credfile
       ruser rpass

Now, When I try to connect to RServe, passing username/password to login method, it does not work.I started Rserve using 'R CMD Rserve –RS-port 6311 –no-save –RS-encoding utf8'
---
A small snippet – 
               Rconnection *rc = new Rconnection("xx.xxx.xx.xx",6311);
               rc->connect();
	       rc->login("ruser","rpass");
 
I am using the cpp client and using the files from src/client/cxx/ folder. If I disable 'auth' in Rserv.conf, the code works as expected. Can someone help me finding out what am I missing?

Thank you.

**Comment by uniqueinput** [comment]
Same for me.
After looking into the Source Code of the Java RServe Client it seems to me that this is not supported/implemented yet. 
E.g. CMD_secLogin and CMD_keyReq are not implemented in the Java RServe Client. 
However, in RSClient (the R Package) it is implemented and works like a charm.

Hopefull it will be supported by the Java RServe Client soon, too.

Thanks and best regards

**Comment by ecs-hk** [comment]
I realize this is more than one year old, but are either/both of you still seeing this issue if testing with RSclient? I ran into this problem myself because I was following an (outdated) Rserv.conf tutorial which specified that `pwdfile` should be configured like:
```
user
password
```
When I tested this sort of `pwdfile` configuration (above) with Rserve 1.7-3 / R version 3.5.2 I ran into authentication errors no matter what I tried. I finally changed the `pwdfile` format to:
```
user password
```
.. and found that all is well. Here's successful vs. unsuccessful authentication attempt output as shown in RSclient (i..e the correct password in this test is "xy"):
```
> c <- RS.connect(host = '192.168.122.1')                                               
> RS.login(c, "rguy", "xy", authkey = RS.authkey(c))                                    
[1] TRUE
> RS.eval(c, getwd())
[1] "/tmp/Rserv/conn9"
> RS.close(c)
NULL

> c <- RS.connect(host = '192.168.122.1')                                               
> RS.login(c, "rguy", "bogus_pass", authkey = RS.authkey(c))                            
rsc_abort: connection closed by peer
Error in RS.login(c, "rguy", "bogus_pass", authkey = RS.authkey(c)) :
  read error - could not obtain response header
```
During that test, in the Rserve.dbg log I see:
```
CMD=00000007, pars=1
CMD_secLogin: authkey matches, asl payload: 9
Authentication attempt (login='rguy', pwd='xy', pwdfile='/usr/local/etc/r_creds')
Found login 'rguy', checking password.
 - stored pwd = 'xy', md5='3e44107170a520582ade522fa73c1d15', sha1='5f8459982f9f619f4b0d
9af2542a2086e56a4bef'
 - plain password matches.
OUT.sendRespData
```

NB: even though the Rserve.dbg log implies (to me) that MD5 digests or SHA1 digests are acceptable in `pwdfile`, they do not seem to work in practice. I tested both, e.g.:
```bash
printf '%s' 'password_here' | openssl dgst -md5 | cut -d ' ' -f 2
```
.. but authentication failed repeatedly unless I used the cleartext password in `pwdfile`. (I even confirmed that my digest matched what Rserve was looking for, as indicated in its own output.)

**Comment by alusbars** [comment]
Hi community,

I am facing similar authentication issue from different clients - RServeCli2, RServeLink and java client with enabled auth on Rserve and using both plain text and unix crypto auth methods.
I've tested towards different OS distributions and it worked fine for macos ventura, windows 10(only PT) and centos 7, and ubuntu equal or prior to 20.x versions. 
Starting Ubuntu 22.x the authentication both PT and UC doesn't work. 
(On Ubuntu 22.x I've downgraded RServe from 1.8-x to v1.7-x and to v0.6-8)
My only suspicion corresponded to presence of ARuc and ARpt in parameters retrieved by the client from Rserve.
In OS distribution, that definitely worked, I had only 'ARuc and key value' OR ARpt.
But on MacOS Ventura I had both , and the clients worked properly. 
In the client code it's fine to have several auth method, just uc is prioritised over pt.
As it was already mentioned above, RSClient works like a charm, which is no doubt because the RSClient and Rserve contributors are the same people. My appreciation to all contributors.
@s-u could you please take a look to C# and Java clients that connecting to Rserve that is running on latest Debian distributions , or at least give a guide to people , what could be the possible fix for authentication issue ?

**Comment by s-u** [comment]
Please note that this issue was about user error (wrong password file), not any actual issue in Rserve. So if you are encountering a problem, please file a separate issue report with all details including your configuration file and the error you are getting.
