### ISSUE TITLE
Rserve sub-processes memory issue

### ISSUE THREAD

**Issue by Bioswami-nfac** [s-u/Rserve#113]
I have a Java server from which I am calling R functions using c.eval. I use Rserve to do this and preload all libraries using the following call

R CMD Rserver --RS-conf Rserve.conf

The file Rserve.conf has all my loaded libraries. The total memory requirement for this is around 127MB.

The challenge I have is that every time I call a function from within my Java server, a new process is spawned but it looks like the process requires the full 127MB of memory. So with 32GB RAM, roughly, 240 concurrent calls are sufficient to max out the memory usage and brings the server crashing down.

I found this link: [Rserve share library code](https://stackoverflow.com/questions/31433840/rserve-share-library-code) but it talks about exactly what I have been doing. Any help in understanding how to make Rserve work without it loading all libraries for every call would be much appreciated.

**Comment by s-u** [comment]
Rserve uses COW fork on systems that support it (Linux, macOS) so all processes share memory until changes are needed in which case only the affected pages are copied. This makes it extremely efficient at preloading packages and reduces the memory footprint.

So can you explain your issue? Note that tools like top don’t distinguish between shared and private pages so you can’t tell actual memory usage.

**Comment by Bioswami-nfac** [comment]
Thanks for the quick revert. 

Basically we are using R from within Java to do all our computational heavy lifting.
I start the Rserve from the command line and we need to load a lot of libraries. Using 'top' I notice that the process uses about 127MB of RAM.

When we call any R function from within our Java Server using REngine --> Rconnection, we notice that fresh process is spawned , with the same 127MB of RAM. 

The issue with this is that if a number of concurrent users hit our server, (which has 32 GB of RAM), then once around 200 concurrent calls are made, the server runs out of memory and crashes.

I have a feeling we are doing something wrong in the way we are making the R calls. For instance, before every R call, we create a Rconnection object. Should we be doing this? Or should we create ONE R connection object and use the same? We have tried to do this and the connection always closes after some time.

Also, is there a way to specify a maximum of N Rserve processes that can be spawned concurrently? 

Thanks in Advance.

Regards,
Arun

**Comment by s-u** [comment]
Please read my earlier reply - the memory is shred across all the processes.

**Comment by Bioswami-nfac** [comment]
Hi Simon,

I understand what you are saying. However, I also see out of memory errors
on my server and am trying to reconcile the two. I can post the errors from
syslog and that might probably give you an idea of why I am confused.

Regards,

Arun

**Comment by s-u** [comment]
First, Rserve doesn't spawn a fresh process, it uses `fork()` to re-use the existing process which shares all the memory with the previous process.

It entirely depends on the code you use. If your computations themselves use a lot of memory, then you can still easily run out of memory. Only the *initial* content is shared, but, for example, if you just do `m + 1` on a matrix after connection then the entire result is now private to the each of the child processes.

Admittedly, this is hard to trace, because Linux doesn't actually report the amount so shared space, it only reports the total memory which includes the shared pages. Also you have no control in the R code about when something gets duplicated or not. You can try calling `gc()` at the end of pre-loading to minimize the necessity to copy things.
