### ISSUE TITLE
[feature request] add option to define "COOPERATIVE" to configure.ac

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#119]
Hi Simon. Would it be possible to a add flag to configure script to enable "cooperative" mode installation? Something like `--cooperative-mode` which will just define `COOPERATIVE` var.

I know we can define it with `PKG_CFLAGS`, `CFALGS`, etc, but with if it will be within configure script it will simplify installation with `install.packages()`.

Thanks.

**Comment by s-u** [comment]
Cooperative more is unsupported and untested - thus it is not intended to be exposed on `configure`. It was originally construed to work around the deficiencies of Windows, since Windows cannot deal with parallel connections. It defeats the purpose since you can simply use a loop in R to create a cooperative server.
