### ISSUE TITLE
Rserve debug logs

### ISSUE THREAD

**Issue by reminia** [s-u/Rserve#122]
I start Rserve in debug mode, but I didnt find any logs in stdout. 

1. start Rserve in debug mode as below:

Rserve::run.Rserve(debug=TRUE, remote=TRUE)

2. java client connect to this Rserve and execute R code.

3. execute success, but I didnt find any output from Rserve side.

What's wrong ?

**Comment by reminia** [comment]
I get it. Seems when eval has exception, rserve side will logout.

**Comment by s-u** [comment]
Note that run.Rserve() does NOT have a `debug` option, because debug version is a different binary. You can only use `Rserve()` with `debug=TRUE`, so likely you meant

    Rserve::Rserve(debug=TRUE, args="--RS-set remote=enable")


Also it's typically a good idea to use `try({...}, silent=TRUE)` for anything you evaluate from the Java side so you can catch error on the Java side.
