### ISSUE TITLE
Sometimes Rserve no response

### ISSUE THREAD

**Issue by ifo1999** [s-u/Rserve#132]
Hello I appreciate your help to make the webservice via your library.
I wrote same issue before. Someone replied that could I reproduce the condition. But I can not
reproduce the condition that makes the problem. And that problem was not issued again about 6 months. And I got stuck same problem again.

rserve(1.7.3) is running in daemon at the linux OS (CentOS 7)
I ran the rserve at the Rstudio like this "Rserve(args='--vanilla')"
I use the rserve to receive the call from java
Sometimes java call the Rscript but had no response. From java side rconnection was succeed but via eval expression had no response. If it was successfully called I can see script printed from the log. When problems has occurred there was no log
And there was no heavy transaction
CPU and Memory was enough to serve
And there was empty folder in the tmp/Rserve like conn12xxxx and zombie processes like defunct xxx.

I read about the News/Change log like below. 
version 1.8-4
bugfix: when using compute separation on some Linux systems the
        death of the compute process may remain undetected. Rserve
        now actively detects if the compute process has terminated and
        will signal accordingly. The same goes of a compute process
        whose parent has died.

Will it be fixed if I update Rserve verion from 1.7.3 to 1.8.4?

**Comment by s-u** [comment]
You should definitely use the latest version (1.8-6 right now), because there have been many bugfixes since the version you're using which is about 5 years old!

However, your report is completely devoid of any content, so it's impossible to tell what issue you have. If you actually have an issue, please file a proper report with exact output of what goes wrong and how to reproduce it.
