### ISSUE TITLE
[docs] OCAP mode

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#135]
Rserve provides a lot of great features (and I learn a lot by reading source code). However certain features are still hard to understand. Is there any documentation for OCAP mode (I even can't guess for what it stands for)? I've tried to learn from docs/news from https://www.rforge.net/Rserve/ and from source code on github, but unfortunately still struggling to understand.

**Comment by s-u** [comment]
OCAP is Object CAPabilities mode (see https://en.wikipedia.org/wiki/Object-capability_model for the basic concept this has been inspired by). Basically, it guarantees that the client can only execute operations it has been allowed to execute. In the case of Rserve is simply means that you can only call functions that have been provided to the client by the server. Initially, the server exposes only a single function which can then in turn register more functions if it wants to, but can do so conditionally on the parameters. We have introduced it for RCloud (https://rcloud.social) so that you start with a single function whose only purpose is to authenticate and decide which capabilities you are allowed to use. That function is called `oc.init` and typically returns one or more functions (OCAPs) that have been exposed, e.g. a minimal example from `scripts.R`:

```
.GlobalEnv$oc.init <- function(...) {
    ## remove myself from the global env since my job is done
    if (identical(.GlobalEnv$oc.init, oc.init)) rm(oc.init, envir=.GlobalEnv)

    Rserve:::ocap(call.script)
}

call.script <- function(..) { ... }
```

on the client side:

```
> c <- RS.connect("/data/rcloud/run/Rscripts",0)
> str(c)
Class 'RserveConnection' <externalptr> 
 - attr(*, "capabilities")= 'OCref' chr "HDqxjt.K5qUgGMqbEph.j19wuLHU"
> oc.init <- attr(c, "capabilities")
> RSclient::RS.eval.qap(c, as.call(list(oc.init, "foo")))
```

so essentially, you use `Rserve::ocap()`to create references to functions which you can return back to the client and the client can call them just like regular R functions. In OCAP mode you can only evaluate calls to OCAP functions and nothing else:

```
> RSclient::RS.eval.qap(c, 1+1)
Error in RSclient::RS.eval.qap(c, 1 + 1) : 
  command failed with status code 0x61: feature is disabled
```

In addition, OCAP mode is the only mode where you can perform nested calls, i.e. during the evaluation of a OOB message you can call an OCAP.

Finally, OCAPs allow for process separation, i.e., you can have a subprocess (which we call compute process since that's what it's used for) that can register its own OCAPs which are passed down to the it. Those can be blocking without impacting the master process - we use this to separate GUI calls which have to be responsive even if R is busy computing and the actual computation process which can be blocking which R is computing.

**Comment by dselivanov** [comment]
Thank you! will try to play around it.
