### ISSUE TITLE
Error in gzfile(file, mode) : cannot open the connection

### ISSUE THREAD

**Issue by ifo1999** [s-u/Rserve#145]
Hello. I have to tell you in advance that I appreciate for providing the library.

I have an error like below sometimes. 

Could you help me?

Error message
"Error in gzfile(file, mode) : cannot open the connection"
When error has occured I restart the Rserve daemon process and it works fine
1) killall -INT Rserve
2) R CMD Rserve
I can not reproduce this situation

Error location
future::plan('multiprocess', gc = T)
      wordrst <- future.apply::future_lapply(wordlist, function(X, df){
        rst <- df[grep(X, tolower(df$TXTMD)),]
        print(paste("df$TXTMD", df$TXTMD))
        if(NROW(rst) > 0){
          
          rst <- rst[!duplicated(rst$SKU),]
          rst$word <- X
          rst$SKU <- as.character(rst$SKU)
          rst <- rst[,c('SKU', 'word')]
          rst <- as.matrix(rst)
          return(rst)
        } else {
          return(NULL)
        }
        
      }, df = dat_tmart)

Rserve version(1.8.5)

**Comment by s-u** [comment]
You cannot use `future` with `mutliprocess` since it uses `fork()` which disrupts all I/O operations. You can only use self-contained code inside `fork()`ed code and you must guarantee that it performs no I/O operations. This is a limitation of the `muticore` back-end. Do not use `multicore` (either via `parallel` or `future`).
