### ISSUE TITLE
Monitoring via Rserve logs

### ISSUE THREAD

**Issue by Felix-Tr** [s-u/Rserve#169]
How can I extract detailled logging information from the Rserve that can be used further for monitoring?

We use Rserve in our microservices and want to get RED metrics for Prometheus out of Rserve logs by using e.g. [grok exporter](https://github.com/fstab/grok_exporter) or [mtail](https://github.com/google/mtail).
Currently some metrics are generated via the workaround to safe logging information when for example a script is sourced via RS.eval which is not optimal...
By monitoring the Rserve.dbg main process via e.g. `sudo strace -f -T -tt -p<Rserve PID> -s9999 -e write` one can get quite detailled information including the forked PID's of connections and their respective log outputs, for example the connection duration in the following output:
...
strace: Process 32623 attached
[**pid 32623**] **13:23:26.389667** write(1, "**connection accepted.\n**", 21) = 21 <0.000199>
[pid 32623] 13:23:26.390081 write(1, "sending ID string.\n", 19) = 19 <0.000237>
...
[**pid 32623**] **13:32:53.718648** write(1, "**Connection closed by peer.\n**", 27) = 27 <0.000031>
...
However having a seperate process to monitor Rserve is not possible and Rserve needs to be used in production as Rserve.dbg is slower than Rserve. By that one losses the valuable information of connections, sent bytes, and so on and only an Error count could be realised.

From my understanding _ulog_ as mentioned in [61](https://github.com/s-u/Rserve/issues/61) can be used however I don't understand how to configure it. I just added e.g. `ulog ./file.log` to the config but nothing happened... What am I doing wrong?

And Is there something I miss on how I could get logs from Rserve that can be used for monitoring? Thanks in advance

**Comment by s-u** [comment]
`ulog`uses syslog-compatible messages so you point it to a socket or server that can accept syslog messages. You can use any of the standard clients such as `rsyslogd` or I am providing a simple implementation https://github.com/s-u/ulog/tree/master/src/ulogd that works as a single daemon that supports logging into files (including simple log rotation).

So you try
```
ulogd -s /tmp/ulog.socket -v
R CMD Rserve --RS-set ulog=/tmp/ulog.socket
```

The `ulog` system has been introduced to support logging in the OCAP mode since that is what people would use in production for security reasons (e.g. as used by [RCloud](https://github.com/att/RCloud)) to log entry and returns from OCAP calls. Is also usable in client code via the [ulog package](https://github.com/s-u/ulog). However, Rserve itself didn't use it outside of the OCAP mode (other than in the WebSocket proxy).

It is very easy to add logging outside of OCAP, but what exactly would you like to log? I have added very basic logging now so it shows at least server start/end, connection start/end and each message. Is that sufficient for your purpose?

As for debug, yes, you're right debug output is really only intended for debugging, not for monitoring.
