### ISSUE TITLE
eval failed 127, no logging, no stacktrace

### ISSUE THREAD

**Issue by eduarddrenth** [s-u/Rserve#185]
Dear all, since more than a year I have two apps running based on Rserve. I am trying now to update these apps, which fails.
Updates (most important I think): ubuntu 20.04, python 3.8, jdk 11.
- Rconnection.eval gives me "eval failed".
- the command I eval is `source("path-to/load.R")`
- `Rscript path-to/load.R` works fine
- debugging shows I end up here: https://github.com/s-u/REngine/blob/e65ff263cc0b232b56806b6e94ddb4253db8f619/Rserve/protocol/RTalk.java#L234
- I cannot find any logging server side to find out what exactly fails
- tried different combinations of R and Rserve

My questions are

- how can I find more info/logging about what exactly fails?
- What might be the cause of the problem?

Regards, Eduard

**Comment by s-u** [comment]
Regular R rules apply: generally, you should wrap your code with `tryCatch()` or `Rserve.eval()` in order to make sure yours errors are delivered to the client. R will output error on the server side if they are not caught so check the output (`stdout`/`stderr`) of your server process (unless you used OCAP and I/O forwarding in which case the client will get it as OOB messages).

**Comment by eduarddrenth** [comment]
Right.... managed to get a hold of stdout/stderr via `cat /proc/{PID}/fd/1`, `cat /proc/{PID}/fd/2`. That helped to find and solve the problem
