### ISSUE TITLE
Rserve instances locked

### ISSUE THREAD

**Issue by rapofran** [s-u/Rserve#25]
Hi, I'm facing a weird problem: I have a ruby client talking to Rserve, and sometimes (randomly, once or twice in a day) the connection raise a Timeout exception, and from that moment all the commands passed to Rserve are not responding.

I have to manually restart the app, so it re-connects with Rserve.

Do you know where do I have to look? I'm very blind, there's no logs indicating the problem.

**Comment by s-u** [comment]
Do I understand correctly that you're trying to keep up a connection for a very long time? I.e. you're talking about a single client connection? What is your underlying transport? For anything other than local sockets the connection may drop simply due to network issues. There are keep alive options if you use TCP connection, for example.

**Comment by rapofran** [comment]
@s-u thanks for your reply!

No, the connection should not be alive for a very long time, that's the first problem.
I'm using TCP sockets locally.

This is the output of `ps aux | grep Rserve` https://gist.github.com/rapofran/1a3690289c55e470db7c. Is it normal to see many Rserve processes sleeping? and two zombies?

Another thing I see is that the Rserve processes are consuming up to 99% of CPU.

I hope I've explained well myself. Thanks!

**Comment by s-u** [comment]
Sorry, it doesn't really tell me what you're running. Without an example to reproduce I can't really tell what your processes are doing since they are executing R code that the client supplies so it can be anything. Also I still don't know which connection raises the timeout - Rserve itself imposes no timeout so I'm still not sure what you're talking about. The server process just listens and forks, so is the server process getting "stuck"? The only issue I'm aware if is that in 1.8+ you don't want to enable control commands or the server process may get stuck (the new control pipe implementation has its issues and control gets executed between accept runs so that's how it can get stuck) - in 1.7 was ok. On the client side I have not yet seen any issues - but then I don't know anything about the Ruby client.
