### ISSUE TITLE
RServe loads R environment before chroot

### ISSUE THREAD

**Issue by rfaelens** [s-u/Rserve#37]
I am trying to create a self-contained RServe in a chroot jail.
This works perfectly. However, the initial startup of RServe binds to the current /usr/lib64/R/ installation, even if the chroot environment contains another R installation.

This poses problems if the chroot environment has a different R version from the system R version.

RServe should scan the configuration file and execute any chroot *before* loading any other functions/libraries.

**Comment by s-u** [comment]
Sorry, I'm not quite sure I understand the issue - you are setting the environment before Rserve is started (typically using `R CMD`) - it merely uses the R home defined by the environment. Normally, the way `chroot`ed Rserve is used to have the corresponding R setup in the chroot which is typically a subset of the system R. Rserve doesn't "bind" anything itself, it's being linked against whatever R is available - and that happens before it's even run, so it has no control over that. If you want to have an entirely different R setup in your chroot jail, then you have to first chroot into the jail and then start Rserve - there is nothing Rserve itself can do to make that happen itself since it's linked to whatever R you start it with.

**Comment by rfaelens** [comment]
Thanks for the comment. 

Indeed the right approach is to use LD_PRELOAD or other ld "tricks" to make sure RServe binds with the right R dll when run in a chroot environment. RServe links to whatever R the dynamic loader picks out, which is typically the system R.

You can close this as a "won't fix", we will try to make it work by either using LD_PRELOAD or by writing a wrapper to chroot first.

**Comment by s-u** [comment]
`LD_PRELOAD` doesn't sound quite right. R controls the locations that will be loaded using via `R_HOME_DIR` in the initial script and then `$R_HOME_DIR/etc/ldpaths` for the location of libraries, so I would rather make sure those are setup correctly instead.
