### ISSUE TITLE
Close unused connections

### ISSUE THREAD

**Issue by ppiotrow** [s-u/Rserve#39]
Lets say, that I opened 20 connections from Java, but then my application failed without closing them.
The current number of open connections on RServe equals 20
`find / -name "conn*" -print | grep  ".*tmp/Rserv/conn.*" | wc -l`
`> 20`

Then I rerun my Java application and now which opened another 20 connections and now I have 40 connections.
`find / -name "conn*" -print | grep  ".*tmp/Rserv/conn.*" | wc -l`
`> 40`

Is is somehow possible by RServe to detect such situation and cleanup resources?

**Comment by s-u** [comment]
Connections are closed automatically by the OS when your Java process dies (true for any process). Also the presence of the working directory has no relationship to existing connections - use something like `ps ax|grep Rserve`. If you still see dangling connections, please provide a reproducible example since they way how you get into that state is actually important as it doesn't occur normally for reasons above.

**Comment by ppiotrow** [comment]
I usually get this situation when working with RServe hidden by VPN. When my VPN connection dies then OS won't notify RServe about closing connection. When I connect to VPN again and ssh into RServe machine, run `top` I see process representing unclosed connection with allocated memory. I think it may be easily reproduced by just unplugging ethernet cable or switching off wireless access point. 

BTW, when using RSclient from R and having `con` representing connection after I reconnect VPN and call RS.close(con) the memory on RServe is also NOT released.
