### ISSUE TITLE
RS.eval wait=FALSE and ignore collection

### ISSUE THREAD

**Issue by jangorecki** [s-u/Rserve#43]
Considering the case when I need to call a function on server side without fetching the results I can use `RS.eval(..., wait=FALSE)`. But after that I cannot run another calls due to:
```
Error in RS.eval(rsc, x, wait = wait, lazy = lazy) : 
  uncollected result from previous command, remove first
```
Can I ignore collection and proceed with next call somehow?

**Comment by s-u** [comment]
No, because R is not threaded, so you can only run one R command at a given time, so you have to wait until the evaluation finished before submitting the next command. It's not as much about collection (you can always return `NULL`) but rather synchronization of the worker R.

You could add a queue on the client side if you wanted to enqueue commands until the R on the other side is ready to accept them - that's pretty much all you can do.
