### ISSUE TITLE
Allow running as service - Do not detach from parent process

### ISSUE THREAD

**Issue by deric** [s-u/Rserve#56]
I'm trying to run `Rserve` with `daemon disable` however it doesn't work as expected.

From available documentation I couldn't find any way how to force Rserve to behave as a standard Linux daemon, which could be managed by init.d or systemd. Start as normal process, don't detach and terminate on `SIGTERM`.

**Comment by s-u** [comment]
The whole point of a daemon in unix *is* that it detaches and that's also a typical way to do so from `init.d`. So the above makes no sense at all - the default way to run is exactly how Rserve is typically deployed in Linux as a daemon (which is why that's the default).

If you don't want to run Rserve as a daemon, you can disable it as you note above, but it's unclear to me what exactly you mean by "however it doesn't work as expected". What do you expect? How does Rserve depart from your expectation? You'll have to be a bit more specific.

**Comment by deric** [comment]
Yes, you're right, that's the point of a daemon. But it not typical to handle this by the daemon itself. If you have an `init.d` or `systemd` script it stores processes `PID` and eventually checks if process it still running. However in the was as Rserve is written the `init` system grabs wrong PID.
I'm gonna demonstrate this in a simple [runit](http://smarden.org/runit/) script:
```
exec 2>&1
export R_HOME="/usr/lib/R"
exec chpst -uwww-data /usr/lib/R/bin/Rserve --RS-conf /etc/sv/rserve/conf --no-save
```
In this case `runit` will keep restarting the service, because the parent process exited too early. Is this clear now?

**Comment by s-u** [comment]
Not exactly, why don't you use the pid file (see `--RS-pidfile`)? That's the standard way of doing this. Grabbing the PID directly only works for no-daemons for obvious reasons (I have seen some code that tries to infer it by descent but that's always error-prone since it depends on the daemons started).

**Comment by deric** [comment]
Uhm, maybe because it's not documented? `--RS-pidfile` is not shown in `Rserve --help`. Anyway, `runit` doesn't support PID files in way of `init.d`, it grabs PID directly from the process and that's where Rserve doesn't behave properly. Have you tried to write a service definition for `upstart` or `systemd`? You you have an example of `init.d` script?

**Comment by deric** [comment]
Here's an example [init.d file](https://gist.github.com/deric/a3d3ebaaba92fccc749b). It assumes existence of `/etc/sv/rserve/conf`:
```
remote enable
auth disable
maxinbuf 500000
encoding utf8
daemon enable
```

**Comment by dieresys** [comment]
Here is a systemd service for running rserve, made using a lot of strips from different sites:

```
[Unit]
Description=Rserve

[Service]
TimeoutSec=10s
Type=forking
PIDFile=/var/run/rserve/rserve.pid

# Run ExecStartPre with root-permissions
PermissionsStartOnly=true
ExecStartPre=/usr/bin/mkdir -p /var/run/rserve
ExecStartPre=/usr/bin/chown -R nobody:nobody /var/run/rserve

# Run ExecStart with User=nobody / Group=nobody
User=nobody
Group=nobody
ExecStart=/usr/bin/R CMD Rserve --quiet --vanilla --RS-pidfile /var/run/rserve/rserve.pid

[Install]
WantedBy=multi-user.target
```

_Type=forking_ commands **systemd** not to grab the PID from the main process but from the _PIDFile=..._ instead.

**Comment by ylin30** [comment]
@deric @s-u Would you mind to share example cmd to start Rserve with daemon disable? "R CMD Rserve" actually starts Rserve in daemon mode. FYI. I am trying to use Supervisord to control Rserve.

**Comment by jangorecki** [comment]
If the problem is the fact that a worker machine closes because the Rserve process exited, then simple workaround is `R CMD Rserve --RS-conf /etc/Rserve.conf --no-save && /bin/sh -c "while true; do sleep 5; done;"` - described in #47

**Comment by tjdett** [comment]
When trying to use Rserve with [s6](https://skarnet.org/software/s6), I simply couldn't get `daemon disable` to do anything. Tried in main config file, extra config file and `--RS-set` (which emits `unknown option '--RS-set'`).

In the end, I fell back to polling:
```shell
PIDFILE=$(mktemp --tmpdir --suffix=.pid Rserve-XXXX)
R CMD Rserve --quiet --vanilla --RS-pidfile "$PIDFILE"
PID=$(cat "$PIDFILE")
echo "Rserve is running (PID $PID)"
while $(kill -0 $PID)
do
  sleep 0.5
done
echo "Rserve has exited"
```

**Comment by s-u** [comment]
@tjdett it looks like you Rserve is way old, `--RS-set` has been introduced in 1.8-0 and the current version is 1.8-5

**Comment by tjdett** [comment]
@s-u it was a fresh install, but the [current version on CRAN](https://cran.r-project.org/package=Rserve) is 1.7-3, so that explains my confusion. This is a legacy project, and I'm not familiar with R community practices, so it didn't occur to me that there'd be a divergence.

The problem appears to be that s-u/Rserve@75ad99f89699d9a894f0f0a42b6d3fabc59720b8 came after the last CRAN release, so I should have been using `deamon disable` in `/etc/Rserv.conf`.

**Comment by baylisscg** [comment]
Yes that's how you daemonise a process but it's supposed to be done by the init system not the service itself. For some init systems, like launchd or runit, if the service tries to daemonise itself it just won't work. It is prevalent enough for some systems to provide tooling for handling it but it never works quite as reliably.

**Comment by s-u** [comment]
Like noted above, that is supported now.
