### ISSUE TITLE
No partial message support with websockets

### ISSUE THREAD

**Issue by lev-kuznetsov** [s-u/Rserve#59]
Websockets support partial messages on the protocol level. If the message is bigger than maxsendbuf, the server should send in maxsendbuf sized chunks. Currently you get an object too big error (code 4C). Try setting maxsendbuf to 64 (kB) as a test.

**Comment by s-u** [comment]
No, that's not how `maxsendbuf` works - it is entirely unrelated to WebSockets. What `maxsendbuf` governs is the size of the *entire QAP message* in Rserve, because Rserve assembles the message in memory before sending it on the wire. That is necessary because the header contains the full length which is only known after the entire object has been serialized.
