### ISSUE TITLE
RSA public key returned in CMD_keyReq response does not work

### ISSUE THREAD

**Issue by ksobue** [s-u/Rserve#60]
Somehow the public key returned in CMD_keyReq response does not match with the public key generated locally by openssl command from the private key.

The private key was generated with:
`openssl genrsa -out server.key 4096`

Then the public key was generated with:
`openssl rsa -pubout -in server.key -outform der -out server_pub.key`

In Rserv.c, `i2d_RSAPublicKey` function is used in `rsa_gen_resp` function, so I assume public key is returned in DER format and used "-outform der" above. The file size of server_pub.key is always 550 bytes, even when I repeated the above 2 commands.

However, the public key returned in CMD_keyReq response is 526 bytes and the keys does not match.

If I encrypt authkey, username, and password with the local public key, subsequent CMD_secLogin command will succeeed. But it fails to encrypt if the public key returned by the server is used.

**Comment by ksobue** [comment]
If I save the public key from Rserve as test.der, and use the command below to convert to PEM format, I got this error.

```
$ openssl rsa -pubin -inform der -in test.der -pubout -outform pem 
unable to load Public Key
40998:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/crypto/asn1/tasn_dec.c:1341:
40998:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/crypto/asn1/tasn_dec.c:385:Type=X509_ALGOR
40998:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/crypto/asn1/tasn_dec.c:765:Field=algor, Type=X509_PUBKEY
```

**Comment by s-u** [comment]
Yes, the whole world of key storage is confusing which is why I have put together a little write-up on that topic on the [PKI Wiki](https://github.com/s-u/PKI/wiki/KeyNotes).

What Rserve uses is the actual RSA key while what you're are generating in `openssl` is the Subject Public Key Info structure from the X.509 standard which is a wrapped RSA key with an additional layer on top. In PEM format you woudl see the difference in the header - `BEGIN PUBLIC KEY` vs `BEGIN RSA PUBLIC KEY`, but in DER you'd have to look at the ASN.1 payload to see that (c.f. `PKI::ASN1.decode()`). If you want `openssl` to load/save the RSA key use `-RSAPublicKey_in`/`-RSAPublicKey_out` respectively.

**Comment by ksobue** [comment]
Wow, PKI Wiki is such a great resource to understand the keys. Thank you!
