### ISSUE TITLE
RServe without forking or creating independent working directories

### ISSUE THREAD

**Issue by satyadeepthi** [s-u/Rserve#83]
I am using Rserve to call R code from Scala. The R code is across multiple files in a directory. So when I source a single R file from Scala, it internally sources other files. 
For this to work, I need to set the working directory to the directory where all my R source code files exist. 
The problem is RServe appends 'conn<unique ID>' folder name to the working directory in order to support forking mechanism and my files no longer exist in that new directory. So it cannot find the files I am trying to source from Scala. 

Of course this is not a problem in Windows, since Windows does not have the forking mechanism, but it is in Linux.

How can I overcome this problem?

Thanks a lot.

**Comment by hyounesy** [comment]
Have you tried calling setwd("path_to_working_dir") through Rserve before sourcing your R code?

**Comment by satyadeepthi** [comment]
@hyounesy Yes. I did setwd() at the R command prompt and also used the workdir option while calling Rserve

**Comment by hyounesy** [comment]
would you be able to add a print(getwd()) to the first line of the R script being sourced, and see what you get?

**Comment by s-u** [comment]
@satyadeepthi Rserve intentionally changes the working directory after connect specifically so that parallel sessions don't clash. You can however, always have *your code* change to any directory via `setwd()` as @hyounesy suggested. You probably misunderstood - he said correctly * before sourcing your R code* - but after the connection is made.
